# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BGLPointMass <- function(xx, y, W, s, q, maxSteps, hatAlpha, hatBeta, hatInvTauSqStar, invSigAlpha0, hatPiStar, hatLambdaSqStar, hatSigmaSq, aStar, bStar, alpha, gamma, sh1, sh0, progress) {
    .Call(`_robin_BGLPointMass`, xx, y, W, s, q, maxSteps, hatAlpha, hatBeta, hatInvTauSqStar, invSigAlpha0, hatPiStar, hatLambdaSqStar, hatSigmaSq, aStar, bStar, alpha, gamma, sh1, sh0, progress)
}

BGL <- function(xx, y, W, s, q, maxSteps, hatBeta, hatAlpha, hatInvTauSq, invSigAlpha0, hatLambdaSqStar, hatSigmaSq, aStar, bStar, alpha, gamma, progress) {
    .Call(`_robin_BGL`, xx, y, W, s, q, maxSteps, hatBeta, hatAlpha, hatInvTauSq, invSigAlpha0, hatLambdaSqStar, hatSigmaSq, aStar, bStar, alpha, gamma, progress)
}

BL_SS <- function(xx, y, W, maxSteps, hatAlpha, hatBeta, hatInvTauSq, invSigAlpha0, hatPi, hatLambdaSq, hatSigmaSq, aStar, bStar, alpha, gamma, sh1, sh0, progress) {
    .Call(`_robin_BL_SS`, xx, y, W, maxSteps, hatAlpha, hatBeta, hatInvTauSq, invSigAlpha0, hatPi, hatLambdaSq, hatSigmaSq, aStar, bStar, alpha, gamma, sh1, sh0, progress)
}

BLasso <- function(xx, y, W, maxSteps, hatBeta, hatAlpha, hatInvTauSq, invSigAlpha0, hatLambdaSqStar, hatSigmaSq, aStar, bStar, alpha, gamma, progress) {
    .Call(`_robin_BLasso`, xx, y, W, maxSteps, hatBeta, hatAlpha, hatInvTauSq, invSigAlpha0, hatLambdaSqStar, hatSigmaSq, aStar, bStar, alpha, gamma, progress)
}

BRGL_SS <- function(xx, y, W, s, L, maxSteps, hatAlpha, hatBeta, hatTau, hatV, hatSg, invSigAlpha0, hatPi, hatEtaSq, xi1, xi2, r, a, b, sh1, sh0, progress) {
    .Call(`_robin_BRGL_SS`, xx, y, W, s, L, maxSteps, hatAlpha, hatBeta, hatTau, hatV, hatSg, invSigAlpha0, hatPi, hatEtaSq, xi1, xi2, r, a, b, sh1, sh0, progress)
}

BRGL <- function(xx, y, W, s, L, maxSteps, hatAlpha, hatBeta, hatTau, hatV, hatSg, invSigAlpha0, hatEtaSq, xi1, xi2, r, a, b, progress) {
    .Call(`_robin_BRGL`, xx, y, W, s, L, maxSteps, hatAlpha, hatBeta, hatTau, hatV, hatSg, invSigAlpha0, hatEtaSq, xi1, xi2, r, a, b, progress)
}

BRL_SS <- function(xx, y, W, maxSteps, hatAlpha, hatBeta, hatTau, hatV, hatSg, invSigAlpha0, hatPi, hatEtaSq, xi1, xi2, r1, a, b, sh1, sh0, progress) {
    .Call(`_robin_BRL_SS`, xx, y, W, maxSteps, hatAlpha, hatBeta, hatTau, hatV, hatSg, invSigAlpha0, hatPi, hatEtaSq, xi1, xi2, r1, a, b, sh1, sh0, progress)
}

BRL <- function(xx, y, W, maxSteps, hatAlpha, hatBeta, hatTau, hatV, hatSg, invSigAlpha0, hatEtaSq, xi1, xi2, r1, a, b, progress) {
    .Call(`_robin_BRL`, xx, y, W, maxSteps, hatAlpha, hatBeta, hatTau, hatV, hatSg, invSigAlpha0, hatEtaSq, xi1, xi2, r1, a, b, progress)
}

BRSGL_SS <- function(xx, y, W, s, L, maxSteps, hatAlpha, hatBg, hatTau, hatV, hatGamma, invSigAlpha0, hatSsq, hatPi0, hatPi1, xi1, xi2, hatT, a, b, sh0_1, sh0_0, sh1_1, sh1_0, cutoff, progress) {
    .Call(`_robin_BRSGL_SS`, xx, y, W, s, L, maxSteps, hatAlpha, hatBg, hatTau, hatV, hatGamma, invSigAlpha0, hatSsq, hatPi0, hatPi1, xi1, xi2, hatT, a, b, sh0_1, sh0_0, sh1_1, sh1_0, cutoff, progress)
}

BRSGL <- function(xx, y, W, s, L, maxSteps, hatAlpha, hatBeta, hatTau, hatV, hatSg, hatGamma, invSigAlpha0, hatEta1Sq, hatEta2Sq, xi1, xi2, s1, s2, r1, r2, a, b, progress) {
    .Call(`_robin_BRSGL`, xx, y, W, s, L, maxSteps, hatAlpha, hatBeta, hatTau, hatV, hatSg, hatGamma, invSigAlpha0, hatEta1Sq, hatEta2Sq, xi1, xi2, s1, s2, r1, r2, a, b, progress)
}

BSGL_SS <- function(xx, y, W, s, L, maxSteps, hatAlpha, hatBg, hatSigmaSq, hatGamma, invSigAlpha0, hatSsq, hatPi0, hatPi1, hatT, sh0_1, sh0_0, sh1_1, sh1_0, c, d, cutoff, progress) {
    .Call(`_robin_BSGL_SS`, xx, y, W, s, L, maxSteps, hatAlpha, hatBg, hatSigmaSq, hatGamma, invSigAlpha0, hatSsq, hatPi0, hatPi1, hatT, sh0_1, sh0_0, sh1_1, sh1_0, c, d, cutoff, progress)
}

BSGL <- function(xx, y, W, s, L, maxSteps, hatAlpha, hatBeta, hatInvTauSq, hatInvGammaSq, invSigAlpha0, hatLambdaSqT, hatLambdaSqG, hatSigmaSq, s1, s2, r1, r2, a, b, progress) {
    .Call(`_robin_BSGL`, xx, y, W, s, L, maxSteps, hatAlpha, hatBeta, hatInvTauSq, hatInvGammaSq, invSigAlpha0, hatLambdaSqT, hatLambdaSqG, hatSigmaSq, s1, s2, r1, r2, a, b, progress)
}

#' @export
rtnorm <- function(mu, sigma) {
    .Call(`_robin_rtnorm`, mu, sigma)
}

#' @export
rtnorm0 <- function(mu, sigma) {
    .Call(`_robin_rtnorm0`, mu, sigma)
}

